version: '3.8'

services:
  frontend:
    build:
      context: .
      target: development
    ports:
      - "3002:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
      - VITE_WS_URL=ws://localhost:8000/ws
      - VITE_NODE_ENV=development
    command: npm run dev
    networks:
      - frontend_network

  # Optional: Add nginx proxy for production testing
  nginx:
    build:
      context: .
      target: production
    ports:
      - "8080:80"
    depends_on:
      - frontend
    networks:
      - frontend_network

networks:
  frontend_network:
    driver: bridge 